CREATE DATABASE db_weblinhkien;
USE db_weblinhkien;
GO

CREATE TABLE Products(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
	name NVARCHAR(100);
	price FLOAT;
	link_main_image NVARCHAR;
	status INT;
	details NVARCHAR;
)

CREATE TABLE Images(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
	ID_PRODUCTS INT NOT NULL;
	link_sub_image NVARCHAR;
)

CREATE TABLE GroupCategories(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
	NAME NVARCHAR(50);
	CATEGORY NVARCHAR;
)

CREATE TABLE Category(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
	NAME NVARCHAR(50);
)

CREATE TABLE Details(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
	ID_PRODUCTS INT NOT NULL;
	DESCRIPTION NVARCHAR;
	CONTENT NVARCHAR;
	DATE_CREATE DATE;
)

CREATE TABLE Users(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
	USERNAME VARCHAR(20) NOT NULL;
	EMAIL VARCHAR;
	ADDRESS NVARCHAR;
	FULLNAME NVARCHAR;
	BIRTHDAY DATE;
	AVATAR VARCHAR;
	PHONE_NUMBER NUMBER;
)

CREATE TABLE Orders(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
	ID_USER INT;
	ID_PRODUCTS INT NOT NULL;
	DATE_ORDER DATE;
	STATUS INT;
)

CREATE TABLE OrderDetail(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
	QUANLITY INT;
	TOTAL_MONEY FLOAT;
	DATE_ORDER DATE;
	PAYMENT_METHOD INT;
	IS_COUPON BOOLEAN
)

CREATE TABLE Favorites(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT;
	ID_PRODUCTS INT NOT NULL;
	ID_USER INT NOT NULL;
)

------------------------------------------------
GO
SELECT * FROM Products;